server:
  port: 80
spring:
  application:
    name: CLOUD-CONSUMER-FEIGN80

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用 负载均衡
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka单机
      defaultZone:  http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/   #集群


#设置feign 客户端超时时间（openFeign默认支持ribbon）
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000
logging:
  level:
    # 选择具体接口的方法 的日志输出 级别为debug
    com.atou.springcloud.service.PaymentFeignService: debug

